### ISSUE TITLE
Implement all API endpoints of dart-nextcloud

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#1]
See https://github.com/jld3103/dart-nextcloud/tree/master/lib/src. There will definitely be breaking changes, but we need all endpoints so it's possible to migrate at all.  

- [x] core: autocomplete user (https://github.com/jld3103/dart-nextcloud/blob/0cc8e1df7ef8b4b4407d4f8c5271453fd6149e24/lib/src/autocomplete/client.dart#L19)
- [x] core: avatar (https://github.com/jld3103/dart-nextcloud/blob/0cc8e1df7ef8b4b4407d4f8c5271453fd6149e24/lib/src/avatar/client.dart#L18)
- [ ] core: preview by file id (https://github.com/jld3103/dart-nextcloud/blob/0cc8e1df7ef8b4b4407d4f8c5271453fd6149e24/lib/src/preview/client.dart#L59)
- [ ] core: thumbnail (https://github.com/jld3103/dart-nextcloud/blob/0cc8e1df7ef8b4b4407d4f8c5271453fd6149e24/lib/src/preview/client.dart#L145)
- [ ] files_sharing: sharees (https://github.com/jld3103/dart-nextcloud/blob/0cc8e1df7ef8b4b4407d4f8c5271453fd6149e24/lib/src/sharees/client.dart)
- [ ] talk (https://github.com/jld3103/dart-nextcloud/tree/0cc8e1df7ef8b4b4407d4f8c5271453fd6149e24/lib/src/talk)

**Comment by sonigeez** [comment]
what's update on talk APIs?

**Comment by provokateurin** [comment]
They are work in progress: https://github.com/provokateurin/nextcloud-neon/blob/feature/openapi-demo/specs/spreed.json
I assume they will be available in about two months, but no promises given ;)

**Comment by provokateurin** [comment]
@Leptopoda this should be promoted to the 1.0 release milestone as we want to publish the package then and it would be bad if we wouldn't have all APIs implemented in the new version, right? Not sure if Talk will make the cut though, that could take some more time. It doesn't really matter though because the current package only implements an old version of the Talk API which we are never going to implement anyway.

**Comment by provokateurin** [comment]
The missing APIs would all be ticked off once we have https://github.com/provokateurin/nextcloud-neon/issues/417

**Comment by provokateurin** [comment]
@sonigeez The Talk work hasn't been merged yet, but we now have the infrastructure to work with generated OpenAPI specs. It should be done in less than a month, but it depends on how fast the reviewing goes (though we can just depend on the work-in-progress code if needed).

**Comment by sonigeez** [comment]
Thanks for update @provokateurin

**Comment by provokateurin** [comment]
https://github.com/nextcloud/spreed/pull/10186 is there! As I said it will probably take some time to get it reviewed and merged. If it is important for you, we could use the specs from that PR as I expect them to not change a lot (maybe only some comments).

**Comment by provokateurin** [comment]
@sonigeez With https://github.com/nextcloud/neon/pull/980 being merged we now have full Talk support in the nextcloud package!
