### ISSUE TITLE
Allow uploading files while preserving the actual lastModified date

### ISSUE THREAD

**Issue by adil192** [provokateurin/nextcloud-neon#174]
My app [Saber](https://github.com/adil192/saber) uses the last modified date of files to sync. Currently when a file is uploaded, its last modified date on the server is set to the upload time.

### Proposition
```dart
// before
await webdav.upload(bytes, filePath);
// after (optional {DateTime? lastModified} parameter)
await webdav.upload(bytes, filePath, lastModified: someDateTime);
```

### Alternatives I've considered
I've tried setting the lastModified props like this, but it didn't show any change in the Nextcloud web interface.
```dart
// upload file
await webdav.upload(bytes, filePath);

// set lastModified to match local file
await webdav.updateProps(filePath, {
  WebDavProps.davLastModified.name: someDateTime.toString(),
  WebDavProps.ncUploadTime.name: someDateTime.toString(),
});
```

***

https://github.com/nextcloud/server/issues/15192

> > I can add that uploading files into nextcloud by using WebDAV also doesn't preserve the original timestamps.
>
> not technically possible because the Webdav protocol doesn't include the local modification time
>
> Nextcloud has a custom header X-OC-Mtime that the desktop client and the web UI sets to preserve it.
> Third party clients would need to be modified to also pass this...

I'm not well-versed on Nextcloud but perhaps we need to use something other than webdav?

***

The Nextcloud desktop client sets the header like [this](https://github.com/nextcloud/desktop/blob/040507fce6851aa7f7d0b17aeedbdc20aa0143e9/src/libsync/propagateupload.cpp#L574):

```c++
QMap<QByteArray, QByteArray> PropagateUploadFileCommon::headers()
{
    QMap<QByteArray, QByteArray> headers;
    headers["OC-Async"] = "1";
    headers["Content-Type"] = "application/octet-stream";
    headers["X-OC-Mtime"] = QByteArray::number(qint64(_item->_modtime));
```

**Comment by provokateurin** [comment]
I'm on vacation right now, but I'll look into it when I'm back. Updating the date via props should definitely work, maybe you need to use a different format?

**Comment by adil192** [comment]
I tried both `someDateTime.toString()` and `someDateTime.toIso8601String()`. I wasn't sure what format Nextcloud accepted but didn't know where to look to find out

**Comment by adil192** [comment]
Just tried this DateFormat but no luck
https://github.com/provokateurin/nextcloud-neon/blob/e916fcd8f8bfe840f96f68145a2e32c994404a40/packages/nextcloud/lib/src/webdav/file.dart#L79
```dart
DateFormat('E, d MMM yyyy HH:mm:ss', 'en_US').format(lastModified);
```

**Comment by provokateurin** [comment]
Hey sorry, I didn't have the time yet. I hope I can look at it this or next week.

**Comment by adil192** [comment]
> Hey sorry, I didn't have the time yet. I hope I can look at it this or next week.

There's no rush, this is a really low priority feature request from my end :)

**Comment by provokateurin** [comment]
I found out that modifying the last modified time via the prop is not possible since it is readonly. The only way is to set it at upload time like I did it in the PR.
