### ISSUE TITLE
Investigate melos

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#177]
https://github.com/invertase/melos could be better than mono_repo

**Comment by Leptopoda** [comment]
It even natively supports fvm:
https://melos.invertase.dev/~melos-latest/configuration/overview#sdkpath

**Comment by provokateurin** [comment]
I think using melos and mono_repo together is the way to go. mono_repo really makes the CI parts easier so I want to keep it for that.

**Comment by Leptopoda** [comment]
After some investigation I can see how mono_repo generates clean separated CI configs but I think that the potential of melos is also big.

We can specify commands for everything we need (linting, formating and testing) and then run `melos run lint`, `melos run format-check` and `melos run analyze` in CI.

a really advanced use case is what the firebase team does https://github.com/firebase/flutterfire/blob/master/melos.yaml

and we also get fvm support

**Comment by provokateurin** [comment]
Hm yeah that's quite cool. We can drop mono_repo if we have a good replacement for the CI parts
