### ISSUE TITLE
Upgrade `intl` to ^0.18.0

### ISSUE THREAD

**Issue by adil192** [provokateurin/nextcloud-neon#195]
Hi, please can you upgrade `intl` in the `nextcloud` package?

**Comment by provokateurin** [comment]
Not possible right now, because flutter_localizations (from flutter sdk) in neon depends on intl 0.17.0 :/ You can just override the version in your package using the dependency_overrides.

**Comment by adil192** [comment]
Thanks, I didn't know about dependency_overrides
