### ISSUE TITLE
Authentication problem on WebDav

### ISSUE THREAD

**Issue by muelleel** [provokateurin/nextcloud-neon#196]
Hey, 
not sure if this fits here or if this is an problem on my side or on your side but I get the following error when interacting with WebDav:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NextcloudApiException(statusCode: 401, headers: {}, body: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No public access to this resource., No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
</d:error>
)
#0      WebDavClient._send (package:nextcloud/src/webdav/client.dart:57:7)
<asynchronous suspension>
#1      WebDavClient.ls (package:nextcloud/src/webdav/client.dart:230:22)
<asynchronous suspension>
```

I've tried to set the header manually with the following:
```
client.baseHeaders.putIfAbsent("Authorization", () => "Basic yyy=");
client.authentication?.headers.putIfAbsent("Authorization", () => "Basic yyy=");
client.webdav.rootClient.baseHeaders.putIfAbsent("Authorization", () => "Basic yyy=");
```

The code I'm using
```
var client = NextcloudClient("https://xxx", username: "xxx", password: "yyy");

//client.baseHeaders.putIfAbsent("Authorization", () => "Basic yyy=");
//client.authentication?.headers.putIfAbsent("Authorization", () => "Basic yyy=");
//client.webdav.rootClient.baseHeaders.putIfAbsent("Authorization", () => "Basic yyy=");

client.webdav.ls("/").then((value) => () {
  log("TEST");
  value.forEach((element) {
    log(element.name);
  });
});
```

Any ideas on this?
Some help on this would be nice :)

EDIT: Deleted personal information

**Comment by provokateurin** [comment]
Your code looks correct, I'll take a look soon.

**Comment by provokateurin** [comment]
Ah found the issue! You need to set the `loginName`. I know this is quite confusing, but there is a difference between the `loginName` and `username` :/ This should probably be documented better. I think it would be possible to fallback to using `username` if `loginName` isn't set, do you think that would help?

**Comment by muelleel** [comment]
Thanks for looking into it, I will try it ASAP.

> This should probably be documented better. I think it would be possible to fallback to using username if loginName isn't set, do you think that would help?`

Yeah, a fallback would be great! It would likely prevent confusion in the future :+1:

**Comment by muelleel** [comment]
setting loginName solved the specific error.

But now the future of methods like "ls" are never resolved

```
    log("WEBDAV");
    client.webdav.ls("/").then((value) => () {
      log("GOT RESULT");
      value.forEach((element) {
        log(element.name);
      });
    });
```

When I run it, only "WEBDAV" gets printet, nothing else - no error...

I've tested it with different users on different servers, I also tried to find the problem with the debugger by stepping trough, but I could not find anything suspicious. 

Can someone confirm that my snippet is Working, or confirm that I'm using the library the right way?

**Comment by provokateurin** [comment]
Are you just putting this in your main method? Then you need to still await the call, otherwise the program exits before the future is done.

**Comment by muelleel** [comment]
No, I've tested it in a larger application - with other futures in the same place - the Program does not exit on its own.

**Comment by provokateurin** [comment]
Uhm your code has `(value) => () {...}` which will never be executed. It has to be `(value) {...}`.

**Comment by muelleel** [comment]
Uhm... yes
knew I would embarrass myself ._.
Thank you very much!
