### ISSUE TITLE
`client.provisioningApi.getCurrentUser()` error

### ISSUE THREAD

**Issue by adil192** [provokateurin/nextcloud-neon#226]
```dart
  type 'Null' is not a subtype of type 'String' in type cast
  package:nextcloud/src/nextcloud.openapi.g.dart 1872:34  _$NextcloudProvisioningApiUserDetailsFromJson
  package:nextcloud/src/nextcloud.openapi.dart 4723:7     new NextcloudProvisioningApiUserDetails.fromJson
  package:nextcloud/src/nextcloud.openapi.g.dart 1935:47  _$NextcloudProvisioningApiUser_OcsFromJson
  package:nextcloud/src/nextcloud.openapi.dart 4833:7     new NextcloudProvisioningApiUser_Ocs.fromJson
  package:nextcloud/src/nextcloud.openapi.g.dart 1951:43  _$NextcloudProvisioningApiUserFromJson
  package:nextcloud/src/nextcloud.openapi.dart 4858:7     new NextcloudProvisioningApiUser.fromJson
  package:nextcloud/src/nextcloud.openapi.dart 1217:43    NextcloudProvisioningApiClient.getCurrentUser
```

This is the function that I'm using:
```dart
  @visibleForTesting
  static Future<Quota?> getStorageQuota() async {
    final client = NextcloudClientExtension.withSavedDetails();
    if (client == null) return null;

    final user = await client.provisioningApi.getCurrentUser();
    Prefs.lastStorageQuota.value = user.ocs.data.quota;
    return Prefs.lastStorageQuota.value;
  }
```

**Comment by provokateurin** [comment]
Could you please pin your dependency to a git hash here: https://github.com/adil192/saber/blob/3fa2944c8cfbbe7b13a3ae428f3348b1d9dbd054/pubspec.yaml#L67-L70
Not sure if this is the problem, but in 25.0.4 the `storageLocation` was made nullable due to a security issue. The latest lib already has that fixed, so if you upgrade it should work.

**Comment by adil192** [comment]
> Not sure if this is the problem, but in 25.0.4 the `storageLocation` was made nullable due to a security issue. The latest lib already has that fixed, so if you upgrade it should work.

I was on 25.0.4 before and I've just upgraded to 25.0.5 but still get the error. I'm not sure what you mean by the latest lib but I'm on the latest commit (cc3b6df6b2ab6d46a3ffe6580df57288c6631161)

**Comment by adil192** [comment]
25 seems to still be the latest stable release available to me, but yeah I'll pin the dependency until I can upgrade. Thanks for your help :)
```
[nc.saber.adil.hanney.org]$ php updater/updater.phar
Nextcloud Updater - version: v25.0.3-2-gd49ee0d

Current version is 25.0.5.

No update available.

Nothing to do.
```

**Comment by provokateurin** [comment]
https://github.com/nextcloud/server/releases/tag/v26.0.0
