### ISSUE TITLE
Bug: broken loginFlow

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#235]
Looks like #232 broke the loginFlow by requiring authentication being set for requesting login.

```bash
I/flutter ( 7686): Exception: Missing authentication for basic_auth
I/flutter ( 7686): #0      NextcloudCoreClient.initLoginFlow (package:nextcloud/src/nextcloud.openapi.dart:250:7)
I/flutter ( 7686): #1      LoginBloc._setServerURL (package:neon/src/blocs/login.dart:78:40)
I/flutter ( 7686): <asynchronous suspension>
```

I can reproduce this on master with both the neon and cookbook app.

**Comment by provokateurin** [comment]
Ah, I oversaw that one because it has no tests (I should really add some). Just set `security: []` for the operation (also for the other login flow operations). Could you submit that as a fix? Otherwise I'll do it tomorrow.
