### ISSUE TITLE
LoginFlow password manager support

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#283]
We currently use webview_flutter to launch the NC loginFlowV2.

This means we currently don't support password managers (or at least it doesn't work on my android device).
I haven't found a way to support this with the current implementation. We should explore a different way to login:
1. launch the default browser
2. Launch the browser in a webview

Researching this I noticed that google disallows NativeWebView login and requires a browser since 2016 [google blog](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html)

---

I haven't tested it since I don't have play services on my phone but I'd guess that yubikeys are also not supported for NativeWebView and only in browsers but I might be wrong on that one.

**Comment by provokateurin** [comment]
I remember someone at Nextcloud told me to open the browser, because it will help in odd configuration cases with proxy or other authentication providers. Since we already open the browser on platforms that don't support webviews, it would be the easiest way to do it.

**Comment by Leptopoda** [comment]
We should probably rename this issue. And prioritize it a bit.

While doing rudimentary testing for #345 I rediscovered a nasty limitation of our current webview. We can't really login multiple users on the same instance with the webview as it somehow keeps the cookies and when trying to login with another account the webview is already logged in with thte first one.
