### ISSUE TITLE
[Queastion]: Use of null aware spread operator (CodeStyle)

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#288]
Currently we don't use the spread operator nullable:

https://github.com/provokateurin/nextcloud-neon/blob/f35fb73c49cbd69133b98c664be8d12263f37d08/packages/dynamite/lib/src/openapi_builder.dart#L667-L672

https://github.com/provokateurin/nextcloud-neon/blob/f35fb73c49cbd69133b98c664be8d12263f37d08/packages/neon/neon/lib/src/widgets/list_view.dart#L32-L34

We could replace both types (and maybe even more) with nullaware spread operators like:
```dart
final list = [
   ...?a, 
   ...?b,
   ...?topFixedChildren, 
];

```

@provokateurin What do you think about this? IMO this is way cleaner but I think I already asked you once about the second type and you said you prefer it?

**Comment by provokateurin** [comment]
Good idea, I didn't know that was possible!
