### ISSUE TITLE
Cleanup localizations

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#304]
- Split them per app
- Cleanup unused entries
- Rename the keys have them more structured

**Comment by provokateurin** [comment]
It will be a little annoying, since they won't get automatically regenerated when running the app in debug mode. @Leptopoda any ideas on how to solve this problem? For the app I just duplicated the l10n.yaml file and pointed it to the neon package, but that is not an option here. Maybe some symlink trickery could work, but I'll have to investigate that.

**Comment by Leptopoda** [comment]
Symlink won't work here as flutter-gen would find multiple flies with the same language :/

like neon_en.arb, neon_files_en.arb would both have the same `"@@locale": "en",` key.

**Comment by provokateurin** [comment]
I found https://github.com/flutter/flutter/issues/107157

**Comment by provokateurin** [comment]
I think we just have to live with the fact that there are multiple arb files (until the linked issue is completed). I'd add a script that just runs `flutter gen-l10n` in all packages that have localizations. Not a great DX, but it will improve the architecture because right now it's not great.

**Comment by Leptopoda** [comment]
We'll also have to see what to do about transifex not supporting arb.
We might need to write a simple parser nevertheless :(

**Comment by provokateurin** [comment]
Yeah, but that's for later :)
