### ISSUE TITLE
neon:  Theme switching when changing accounts

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#317]
Moving the themeNotifier into the bloc made the theme not switch on account switching.
Looks like the capabilities are only fetched once per app start per account.

Having multiple accounts will enable the correct theme on the first account checkout but not on subsequent.

---

I won't have much time and am not that familiar with our blocs yet so feel free to tackle this.

**Comment by provokateurin** [comment]
There are still problems. When I open the settings weird things start to happen and I randomly get the wrong theme etc.
