### ISSUE TITLE
Broken built_value changes

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#321]
The following parameter
```json
{
    "name": "subadmin",
    "in": "query",
    "description": "Groups where the user is subadmin",
    "schema": {
        "type": "array",
        "items": {
            "type": "string"
        },
        "default": []
    }
},
```
generates this code
```dart
final BuiltList<String> subadmin = const [],
```
which is not valid.

**Comment by Leptopoda** [comment]
Ok just had a look and the problem is that we need the default value (as a const) in the parameter list of an operation.

I think it is valid here to just make the parmeter a plain `List` so the caller would need to pas `builtListValue.toList()`.

**Comment by Leptopoda** [comment]
https://github.com/provokateurin/nextcloud-neon/blob/6531b2ada799a158c58afeeb11dea168512bdb7c/packages/dynamite/dynamite/lib/src/type_result/object.dart#L21

Hard coded variable name :grimacing:

I'll make a few cleanups (I might get to it today but can't promise anything before Tuesday)

**Comment by provokateurin** [comment]
I pushed the openapi-automatic branch with the broken code. You can use it check your fix.

**Comment by provokateurin** [comment]
I'm pretty sure https://github.com/provokateurin/nextcloud-neon/blob/6531b2ada799a158c58afeeb11dea168512bdb7c/packages/dynamite/dynamite/lib/src/type_result/map.dart#L13 should be `MapBuilder`.

**Comment by provokateurin** [comment]
I get `Bad state: No serializer for '_$ContentString<BuiltList<int>>'.` for
```json
                    {
                        "name": "shareTypes",
                        "in": "query",
                        "description": "Types of shares to search for",
                        "schema": {
                            "type": "string",
                            "contentMediaType": "application/json",
                            "contentSchema": {
                                "type": "array",
                                "default": null,
                                "items": {
                                    "type": "integer",
                                    "format": "int64"
                                },
                                "description": "Types of shares to search for"
                            }
                        }
                    },
```
although the serilizers contain
```dart
      ..addBuilderFactory(
        const FullType(ContentString, [
          FullType(BuiltList, [FullType(int)])
        ]),
        ContentString<BuiltList<int>>.new,
      )
```

**Comment by Leptopoda** [comment]
> I get Bad state: No serializer for '_$ContentString<BuiltList<int>>'. for

haven't had the time to look into it  but did this happen using one of `serializeNextcloud/deserializeNextcloud`?

**Comment by provokateurin** [comment]
Nope, it's this one: https://github.com/provokateurin/nextcloud-neon/blob/442e3f382618a57a79eb30990da07f782987f0df/packages/nextcloud/test/core.dart#L66
