### ISSUE TITLE
Expose the currently supported Nextcloud version

### ISSUE THREAD

**Issue by adil192** [provokateurin/nextcloud-neon#322]
Following #226 the `nextcloud` package only supports Nextcloud 26.
I'm adding a check to my app to tell the user about this, but it would be better if the current supported Nextcloud version was stored in your repo rather than mine.

## Static field for current supported Nextcloud version
It would also be nice if you stored the current supported Nextcloud version, so I could do something like this:
```dart
print('Only Nextcloud ${NextcloudCoreServerStatus.supportedVersion} is supported');
```
rather than hardcoding in 'Only Nextcloud 26'.

## My current code
```dart
final NextcloudCoreServerStatus status;
try {
  status = await client.core.getStatus();
} catch (e) {
  throw NcLoginFailure();
}
if (!status.version.startsWith('26.')) { // <- here
  throw NcUnsupportedFailure('Only Nextcloud 26 is supported!');
}
```

## Proposed code 1
```dart
final NextcloudCoreServerStatus status;
try {
  status = await client.core.getStatus();
} catch (e) {
  throw NcLoginFailure();
}
// here [versionSupportedByPackage] is a boolean for whether [status.version] is 26.*
if (!status.versionSupportedByPackage) {
  throw NcUnsupportedFailure('Only Nextcloud 26 is supported!');
}
```

## Proposed code 2 (preferred)
```dart
final NextcloudCoreServerStatus status;
try {
  status = await client.core.getStatus();
} catch (e) {
  throw NcLoginFailure();
}
// here [versionSupportedByPackage] is a string (which would currently be '26')
if (!status.version.startsWith(NextcloudCoreServerStatus.versionSupportedByPackage)) {
  throw NcUnsupportedFailure('Only Nextcloud ${NextcloudCoreServerStatus.versionSupportedByPackage} is supported!');
}
```

**Comment by provokateurin** [comment]
There already is a check for the supported versions (you need to check core for the server version): https://github.com/provokateurin/nextcloud-neon/blob/main/packages/nextcloud/lib/src/version_supported.dart
We could extend it to also expose the supported version so that it can be told to the user. Does that work for you?

**Comment by adil192** [comment]
Yes that's perfect, thank you
