### ISSUE TITLE
Local path to `dynamite_runtime` in non-local pubspec

### ISSUE THREAD

**Issue by adil192** [provokateurin/nextcloud-neon#326]
When trying to upgrade the `nextcloud` package in Saber (from a525503d2a24ae1840433858b1547c0ca6e23197 to the latest commit), I get this error:
```
$ flutter pub upgrade --major-versions
Error on line 15, column 11: Invalid description in the "nextcloud" pubspec on the "dynamite_runtime" dependency: "../dynamite/dynamite_runtime" is a relative path, but this isn't a local pubspec.
   ╷
15 │     path: ../dynamite/dynamite_runtime
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

**Comment by provokateurin** [comment]
Meh @Leptopoda we forgot to think about that.

**Comment by provokateurin** [comment]
Maybe we should drop the runtime package and just import dynamite in the generated code. I don't think it has much downsides other than adding the dependencies used for the code generator.

**Comment by Leptopoda** [comment]
I don't think this would change anything.

We still import dynamite as a local path so the same error would be shown.

This is only possible rn as we have dynamite as a dev dep but as soon as we bump it to a normal one (what we would need) we get the same error.

**Comment by Leptopoda** [comment]
Actually I did think about that but I must accidentally have added the `publish_to: none` flag to the nextcloud lib.

**Comment by provokateurin** [comment]
Ah yes you are right. I think one possible solution would be to add a `dependency_overrides` for `dynamite_runtime`

**Comment by provokateurin** [comment]
You need to do it like this:
```yaml
dependency_overrides:
  dynamite_runtime:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/dynamite/dynamite_runtime
      ref: COMMIT
```
Replace `COMMIT` with the same commit hash that you use for importing the nextcloud package.

**Comment by provokateurin** [comment]
Ah that sucks. Then the best way right now is probably to add it as a submodule and require the package by path.

**Comment by provokateurin** [comment]
@Leptopoda we could also eliminate the runtime package and generate the content string things for the unit tests separately.

**Comment by Leptopoda** [comment]
I just had a look at how other repos handle this:
https://github.com/google/built_value.dart/blob/master/built_value_generator/pubspec.yaml

It looks like they use a real dependency (in our case we'd use a git dependency) and then override the dep with a local path.

The only downside would be that we might forget to update the git ref and consumers of our lib would then use a new nextcloud version with an outdated dynamite_runtime one.
In that case they can open an issue/pr or they should be able to override it themselves (overriding a git dep with another git one should be possible shouldn't it?).

what do you think about this? I really like having it easy to run the CI as especially in the ContentString case I used a TTD approach wich helped me quite a lot there.

**Comment by Leptopoda** [comment]
I'll test this a bit and make a draft PR
