### ISSUE TITLE
WebDav file upload does not upload the files content correctly.

### ISSUE THREAD

**Issue by muelleel** [provokateurin/nextcloud-neon#332]
Hi,

I'm currently trying to upload a file via the WebDavClient to an Nextcloud instance.
Take the following example:

```
    String path = "locationOnAndroidDevice";
    
    WebDavClient client = NextcloudClient("https://nextcloudinstance/", username: "username", password: "password", loginName: "username").webdav;

    log("UPLOAD STARTING: $path");
    File file = File(path);

    showDialog(
      context: context,
      builder: (context) {
        return SimpleDialog(
          children: [
            Image.memory(file.readAsBytesSync()),
          ],
        );
      },
    );

    client.upload(file.readAsBytesSync(), "/${file.path.split(Platform.pathSeparator).last}").then((value) {
      log("UPLOADED ${value.statusCode}");
    });
```

When executed, an Dialog opens with the image correctly displaying in it.
The Log-Output looks aswell promising:
```
[log] UPLOAD STARTING: /data/user/0/myAppId/cache/3455e0fc-8676-4a0e-b3b7-0e99ad59b73d/IMG_20230506_141031.jpg
[log] WBUNTIS OK
[log] UPLOADED 204
```

After executing it, an dialog opens with the correct image. So the path is correct.
When viewing the root-Folder on the Nextcloud instance I can see a new File, but its size is 0KB. When downloading the File there is nothing in it.
Am I missing something? Any Ideas on this?

Thank you very much!

**Comment by provokateurin** [comment]
Can you please send the complete code for a minimal reproducible sample? The current code doesn't give much context so it's hard to tell what's wrong. Just create a small dart CLI script that shows the problem.

**Comment by provokateurin** [comment]
As you can see in https://github.com/provokateurin/nextcloud-neon/blob/482bff006d4338964c0704600c50434fe76a19b2/packages/nextcloud/test/webdav.dart#L81-L107 we have a unit test that confirms that the upload is working.

**Comment by provokateurin** [comment]
Ok that confirms my assumption. You need to `await` the `client.upload`, otherwise your main function exits before the upload is finished.

**Comment by provokateurin** [comment]
Can you make sure the file doesn't exist before uploading? It looks like status code 204 indicates that a file already exists at the location. Status code 201 indicates the upload was successful.

**Comment by provokateurin** [comment]
I don' think this is a problem with the library. Have you checked if the file is correctly read? You can also check the size after upload by using the unit test code I provided above.

**Comment by provokateurin** [comment]
Sounds similar to https://github.com/bitfireAT/davx5-ose/discussions/326

**Comment by provokateurin** [comment]
We don't use chunked upload (right now), but we could add the content-length header.
