### ISSUE TITLE
Duplicate serializers

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#367]
https://github.com/provokateurin/nextcloud-neon/blob/07eb917f58fc7b63512490e357315e7f3216fb85/packages/nextcloud/lib/src/nextcloud.openapi.dart#L5175 contains a lot of duplicate serializers.

**Comment by provokateurin** [comment]
No, just waisted cpu cycles :)

**Comment by Leptopoda** [comment]
That's negligible as builtvalue internally deduplicates them (it's more cpu at initialization but not at runtime).

I'll make dynamite use a set to avoid this but if you have a look at the generated part file the generated code from builtvalue also has quite many duplications.
