### ISSUE TITLE
Breakup libraries

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#433]
Currently we have many libraries that are used to melt everything together.
They should be broken up into multiple libraries where it makes sense (e.g. all blocs together) or just become standalone files.

**Comment by Leptopoda** [comment]
I think there are two sides we should consider.

1. How do we export them?
2. How do we handle them internally?

We should probably export one per folder
- `package:neon/widgets.dart`
- `package:neon/blocs.dart`
- `package:neon/models.dart` (could also container files from interfaces)
- `package:neon/utils.dart`

Internally I don't think we should use `part` directives at all. But we can still decide this after the first one is done.

**Comment by provokateurin** [comment]
So you would like to have a "summary" file that exports all the other files that are in a given directory instead of using the libraries?

**Comment by Leptopoda** [comment]
That's at least how the flutter framework does it but I don't know if that actually fits us as well.

https://github.com/flutter/flutter/tree/master/packages/flutter/lib

**Comment by provokateurin** [comment]
I see, I think for app implementations it makes a lot of sense to have it like that.

How about the app implementations themselves? I think they can still use a single library using part directives.

**Comment by Leptopoda** [comment]
As they don't really provide a public api the visibility doesn't really matter.
Also changing this after the 1.0 milestone wouldn't be breaking so we can leave them for now.

**Comment by Leptopoda** [comment]
We should probably also break up the nextcloud lib into:
- client
- webdav
- api

with the later two also exposing the first one.

**Comment by provokateurin** [comment]
I'll add that after https://github.com/provokateurin/nextcloud-neon/pull/439 is merged and I have rebased https://github.com/provokateurin/nextcloud-neon/pull/436 onto it. It has pretty big changes and already goes a little bit into that direction.
