### ISSUE TITLE
go_router use query parameters in routes

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#455]
I just noticed that we are using quite many path parameters in our routes. On web those will probably make it into the browser history so we should probably use query parameters where applicable.

I missed it in #452 but things like the serverurl should probably be query parameters.
What do you think?

---

From https://pub.dev/documentation/go_router_builder/latest/:
Parameters (named or positional) not listed in the path of TypedGoRoute indicate query parameters:
```dart
@TypedGoRoute(path: '/login')
class LoginRoute extends GoRouteData {
  LoginRoute({this.from});
  final String? from;

  @override
  Widget build(BuildContext context, GoRouterState state) => LoginScreen(from: from);
}
```

**Comment by provokateurin** [comment]
I think they will appear in the browser history anyways, but it still makes sense to use them :+1:

**Comment by Leptopoda** [comment]
I think this can be closed now.
Right?

**Comment by provokateurin** [comment]
Yep
