### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#493]
We should add one. The one from NC probably good enough:
https://github.com/nextcloud/server/blob/master/CODE_OF_CONDUCT.md

**Comment by provokateurin** [comment]
I agree and also thought about this. I wanted to ask if it is ok to just link to that one, but forgot to do so. I'll ask now

**Comment by provokateurin** [comment]
We can just copy the Nextcloud CoC or point to it, but it was suggested to better use https://www.contributor-covenant.org/. I think either one is fine, but since we will move into the Nextcloud org at some point it would be easier to just use the Nextcloud CoC already.

**Comment by Leptopoda** [comment]
I'm also for the NC one.
